# Generated by Django 6.0.5 on 2026-05-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('especie', models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato')], default='C', max_length=1)),
                ('nome_animal', models.CharField(blank=True, max_length=100, null=True)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('triagem', models.CharField(blank=True, choices=[('verde', 'Verde'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('vermelho', 'Vermelho')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('transcricao', models.TextField(blank=True, null=True)),
                ('segmentos', models.JSONField(blank=True, null=True)),
                ('ocr_pdf', models.TextField(blank=True, null=True)),
                ('analise_exames', models.JSONField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
            ],
        ),
    ]
